// (function () {

//     let divTabela = document.getElementById("tabela-candidatos");
//     let campoNomeCand = document.getElementById("campoNomeCand");

//     let candidatos = [
//         {cargo: "VEREADOR", numeroCandidato: 10010, nomeCandidato: "ÁLVARO MERCADO OJEDA", nomeUrna: "BINHO", partido: "REPUBLICANOS", sqCandidato: 120001015566}, 
//         {cargo: "VEREADOR", numeroCandidato: 13130, nomeCandidato: "JOSE CAVALCANTE DE ALMEIDA", nomeUrna: "VÉIO ZÉ", partido: "PT", sqCandidato: 120001118614}, 
//         {cargo: "PREFEITO", numeroCandidato: 15, nomeCandidato: "LENILSO CARVALHO ANTUNES", nomeUrna: "LENILSO CARVALHO", partido: "MDB", sqCandidato: 120000742354}, 
//         {cargo: "VEREADOR", numeroCandidato: 45678, nomeCandidato: "LAUDO SORRILHA BRUNET", nomeUrna: "LAUDO SORRILHA", partido: "PSDB", sqCandidato: 120000860465}, 
//         {cargo: "VEREADOR", numeroCandidato: 45545, nomeCandidato: "JOSE DOS PASSOS CHAVES DE LIMA", nomeUrna: "JOSE PASSOS", partido: "PSDB", sqCandidato: 120000860474}, 
//         {cargo: "VEREADOR", numeroCandidato: 13515, nomeCandidato: "LIDIA MICHALSKI", nomeUrna: "LIDIA MICHALSKI", partido: "PT", sqCandidato: 120001118626}, 
//         {cargo: "VEREADOR", numeroCandidato: 13332, nomeCandidato: "RUBENS SANTIAGO", nomeUrna: "RUBÃO", partido: "PT", sqCandidato: 120001118625}, 
//         {cargo: "VEREADOR", numeroCandidato: 15150, nomeCandidato: "WELITON GOMES ALVES", nomeUrna: "WELITON GOMES", partido: "MDB", sqCandidato: 120000927964}, 
//         {cargo: "VEREADOR", numeroCandidato: 70070, nomeCandidato: "ADY FERREIRA CABRAL", nomeUrna: "ADY LEITURISTA", partido: "AVANTE", sqCandidato: 120000858829}, 
//         {cargo: "VEREADOR", numeroCandidato: 27000, nomeCandidato: "VERA LUCIA SOARDI DOS SANTOS", nomeUrna: "MISSIONÁRIA VERA", partido: "DC", sqCandidato: 120001201411}, 
//         {cargo: "VEREADOR", numeroCandidato: 15611, nomeCandidato: "JOÃO GOMES ROCHA", nomeUrna: "JOÃOZINHO ROCHA", partido: "MDB", sqCandidato: 120000927963}, 
//         {cargo: "VEREADOR", numeroCandidato: 27047, nomeCandidato: "NEDES ALBERTO DE OLIVEIRA DA SILVA", nomeUrna: "NEDES ELETRICISTA", partido: "DC", sqCandidato: 120001201409}, 
//         {cargo: "VEREADOR", numeroCandidato: 15015, nomeCandidato: "CÉLIO FRANCO DE OLIVEIRA", nomeUrna: "CÉLINHO PADEIRO", partido: "MDB", sqCandidato: 120000927965}, 
//         {cargo: "PREFEITO", numeroCandidato: 45, nomeCandidato: "JOSÉ MARCOS CALDERAN", nomeUrna: "MARCOS CALDERAN", partido: "PSDB", sqCandidato: 120000748340}, 
//         {cargo: "VEREADOR", numeroCandidato: 10146, nomeCandidato: "CRISTIANO DOS SANTOS MELLO", nomeUrna: "CRISTIANO MELLO", partido: "REPUBLICANOS", sqCandidato: 120001015571}, 
//         {cargo: "PREFEITO", numeroCandidato: 20, nomeCandidato: "AMAURI MAZZUCATTO", nomeUrna: "AMAURI MAZZUCATTO", partido: "PSC", sqCandidato: 120000890128}, 
//         {cargo: "VEREADOR", numeroCandidato: 45145, nomeCandidato: "NODAIRES MARTINS RAMIRES", nomeUrna: "NO CONSTRUTOR", partido: "PSDB", sqCandidato: 120000860471}, 
//         {cargo: "VEREADOR", numeroCandidato: 51456, nomeCandidato: "ADRIANO DA SILVA RODRIGUES", nomeUrna: "DADA", partido: "PATRIOTA", sqCandidato: 120001015692}, 
//         {cargo: "VEREADOR", numeroCandidato: 25555, nomeCandidato: "ANDRESKA FLORENTINO FADIGAS", nomeUrna: "ANDRESKA ADVOGADA", partido: "DEM", sqCandidato: 120000890396}, 
//         {cargo: "VEREADOR", numeroCandidato: 70183, nomeCandidato: "RAMONA RODRIGUES CARNEIRO", nomeUrna: "PROFESSORA RAMONA", partido: "AVANTE", sqCandidato: 120000858834}, 
//         {cargo: "VEREADOR", numeroCandidato: 10110, nomeCandidato: "GIAN RICARDO DOS SANTOS", nomeUrna: "PASTOR BUBA", partido: "REPUBLICANOS", sqCandidato: 120001015574}, 
//         {cargo: "VEREADOR", numeroCandidato: 13111, nomeCandidato: "DIOGO DA SILVA JARDIM", nomeUrna: "LEITÃO DO ALTO MARACAJU", partido: "PT", sqCandidato: 120001118617}, 
//         {cargo: "VEREADOR", numeroCandidato: 27123, nomeCandidato: "MARCIO WILLIAN OLIVEIRA BECK", nomeUrna: "MARCIO BECK", partido: "DC", sqCandidato: 120001201406}, 
//         {cargo: "VEREADOR", numeroCandidato: 10100, nomeCandidato: "MICHELLY APARECIDA NUNES", nomeUrna: "MICHELLY NUNES", partido: "REPUBLICANOS", sqCandidato: 120001015577}, 
//         {cargo: "VEREADOR", numeroCandidato: 40789, nomeCandidato: "MARIA CRISTINA ALCANTRA JORGE", nomeUrna: "CRIS", partido: "PSB", sqCandidato: 120001240716}, 
//         {cargo: "VEREADOR", numeroCandidato: 25250, nomeCandidato: "SYDNEY RAMIRES", nomeUrna: "SYDNEY DA AGUA", partido: "DEM", sqCandidato: 120000890411}, 
//         {cargo: "VEREADOR", numeroCandidato: 70770, nomeCandidato: "ETEL RIBEIRO PACHE", nomeUrna: "ETEL PACHE", partido: "AVANTE", sqCandidato: 120000858832}, 
//         {cargo: "VEREADOR", numeroCandidato: 25170, nomeCandidato: "MARIO FERNANDES ROCHA", nomeUrna: "PROF MARIO ROCHA", partido: "DEM", sqCandidato: 120000890404}, 
//         {cargo: "VICE-PREFEITO", numeroCandidato: 27, nomeCandidato: "RAMÃO LUDOVICO DOMINGUES", nomeUrna: "VIKO MOTOS", partido: "DC", sqCandidato: 120001200715}, 
//         {cargo: "VEREADOR", numeroCandidato: 25888, nomeCandidato: "ELENI EGIDIO DOMINGUES", nomeUrna: "LENINHA", partido: "DEM", sqCandidato: 120000890412}, 
//         {cargo: "VEREADOR", numeroCandidato: 10777, nomeCandidato: "JUSSARA DA SILVA MORAES DE JESUS", nomeUrna: "PASTORA SARA", partido: "REPUBLICANOS", sqCandidato: 120001015558}, 
//         {cargo: "VEREADOR", numeroCandidato: 40222, nomeCandidato: "ROSEMEIRE GOMES BARBOSA DE SOUSA", nomeUrna: "MEIRE BARBOSA", partido: "PSB", sqCandidato: 120001240720}, 
//         {cargo: "VEREADOR", numeroCandidato: 45321, nomeCandidato: "LUCIANO FERNANDES FRANCA", nomeUrna: "LUCIANO FRANÇA", partido: "PSDB", sqCandidato: 120000860461}, 
//         {cargo: "VEREADOR", numeroCandidato: 25456, nomeCandidato: "ANTONIO CARLOS DO CANTO BRITES", nomeUrna: "TONHO", partido: "DEM", sqCandidato: 120000890402}, 
//         {cargo: "PREFEITO", numeroCandidato: 10, nomeCandidato: "THIAGO OLEGÁRIO CAMINHA", nomeUrna: "THIAGO CAMINHA", partido: "REPUBLICANOS", sqCandidato: 120001015367}, 
//         {cargo: "VEREADOR", numeroCandidato: 70771, nomeCandidato: "SEBASTIÃO LIMA DOS SANTOS", nomeUrna: "TIÃO PERIGOSO", partido: "AVANTE", sqCandidato: 120000858835}, 
//         {cargo: "VEREADOR", numeroCandidato: 51333, nomeCandidato: "EDINEY GOMES VIEIRA", nomeUrna: "DINEY GOMES", partido: "PATRIOTA", sqCandidato: 120001015685}, 
//         {cargo: "VEREADOR", numeroCandidato: 10302, nomeCandidato: "ELZINI DOS SANTOS", nomeUrna: "ELZINHA", partido: "REPUBLICANOS", sqCandidato: 120001015563}, 
//         {cargo: "VEREADOR", numeroCandidato: 25123, nomeCandidato: "ALICTON MEYER DAL BELLO", nomeUrna: "TOTON PRADENCE", partido: "DEM", sqCandidato: 120000890405}, 
//         {cargo: "VEREADOR", numeroCandidato: 25025, nomeCandidato: "THALES FERREIRA LIMA", nomeUrna: "THALES BUCHMANN", partido: "DEM", sqCandidato: 120000890399}, 
//         {cargo: "VEREADOR", numeroCandidato: 15020, nomeCandidato: "VANDERLEY PORTELA", nomeUrna: "PORTELINHA", partido: "MDB", sqCandidato: 120000927957}, 
//         {cargo: "VEREADOR", numeroCandidato: 40000, nomeCandidato: "MARCIA GOMES CORRÊA MARIZ", nomeUrna: "MARCIA", partido: "PSB", sqCandidato: 120001240711}, 
//         {cargo: "VEREADOR", numeroCandidato: 45777, nomeCandidato: "MAFALDA BARRO LESCANO", nomeUrna: "MAFALDA BARROS", partido: "PSDB", sqCandidato: 120000860473}, 
//         {cargo: "VEREADOR", numeroCandidato: 10300, nomeCandidato: "DEMIS DAVID DA CRUZ TOLEDO", nomeUrna: "DEMIS LOCUTOR", partido: "REPUBLICANOS", sqCandidato: 120001015562}, 
//         {cargo: "VEREADOR", numeroCandidato: 10033, nomeCandidato: "LOURDES MARIA CORONEL SANTOS SUGIMOTO", nomeUrna: "LOURDES CORONEL", partido: "REPUBLICANOS", sqCandidato: 120001015564}, 
//         {cargo: "VEREADOR", numeroCandidato: 27417, nomeCandidato: "TAIS FERREIRA RATIER", nomeUrna: "TAIS RATIER", partido: "DC", sqCandidato: 120001201408}, 
//         {cargo: "VEREADOR", numeroCandidato: 40222, nomeCandidato: "ROSEMEIRE GOMES BARBOSA DE SOUSA", nomeUrna: "MEIRE BAROSA", partido: "PSB", sqCandidato: 120001240714}, 
//         {cargo: "VEREADOR", numeroCandidato: 51234, nomeCandidato: "JOÃO WASHINGTON FAGUNDES DE MORAES", nomeUrna: "JOÃO JW", partido: "PATRIOTA", sqCandidato: 120001015699}, 
//         {cargo: "VEREADOR", numeroCandidato: 51051, nomeCandidato: "MARINICE AZEVEDO PENAJO", nomeUrna: "MARINICE PENAJO", partido: "PATRIOTA", sqCandidato: 120001015694}, 
//         {cargo: "VEREADOR", numeroCandidato: 51555, nomeCandidato: "RENAN TELES DA SILVA", nomeUrna: "RENAN DO PEGA DICA MARACA", partido: "PATRIOTA", sqCandidato: 120001015688}, 
//         {cargo: "VEREADOR", numeroCandidato: 70777, nomeCandidato: "JOSUÉ DA SILVA", nomeUrna: "PASTOR JOSUÉ", partido: "AVANTE", sqCandidato: 120000858826}, 
//         {cargo: "VEREADOR", numeroCandidato: 10456, nomeCandidato: "WALDOMIRO WAGNER", nomeUrna: "PIÁ", partido: "REPUBLICANOS", sqCandidato: 120001015576}, 
//         {cargo: "VEREADOR", numeroCandidato: 45999, nomeCandidato: "GESGISNALDO MARQUES", nomeUrna: "CAFÉ DO GÁZ", partido: "PSDB", sqCandidato: 120000860472}, 
//         {cargo: "VEREADOR", numeroCandidato: 15123, nomeCandidato: "HÉLIO ALBARELLO", nomeUrna: "HÉLIO ALBARELLO", partido: "MDB", sqCandidato: 120000927969}, 
//         {cargo: "VEREADOR", numeroCandidato: 45000, nomeCandidato: "OTTO LUIS LIPKA", nomeUrna: "OTTO", partido: "PSDB", sqCandidato: 120000860475}, 
//         {cargo: "VEREADOR", numeroCandidato: 13222, nomeCandidato: "LUCIANO FRANCO CARDOSO", nomeUrna: "AMENDOIM", partido: "PT", sqCandidato: 120001118619}, 
//         {cargo: "VEREADOR", numeroCandidato: 45789, nomeCandidato: "ROSANE JUNG", nomeUrna: "PROFESSORA ROSANE JUNG", partido: "PSDB", sqCandidato: 120000860476}, 
//         {cargo: "VEREADOR", numeroCandidato: 13456, nomeCandidato: "NEUZA SANTURIÃO DE JESUS", nomeUrna: "NEUZA RENOVAÇÃO", partido: "PT", sqCandidato: 120001118622}, 
//         {cargo: "VEREADOR", numeroCandidato: 40479, nomeCandidato: "MARIA DE FATIMA BRITO BARBOSA", nomeUrna: "FATIMA DA VISTA ALEGRE", partido: "PSB", sqCandidato: 120001240726}, 
//         {cargo: "VEREADOR", numeroCandidato: 40010, nomeCandidato: "VALDECIR BARBOSA DAMACENA", nomeUrna: "RICKO COELHO", partido: "PSB", sqCandidato: 120001240722}, 
//         {cargo: "VEREADOR", numeroCandidato: 15345, nomeCandidato: "ADILSON BATISTA DOS SANTOS", nomeUrna: "ADILSON DA FARMÁCIA", partido: "MDB", sqCandidato: 120000927970}, 
//         {cargo: "VEREADOR", numeroCandidato: 25789, nomeCandidato: "MARGARETE SOUZA BALTA", nomeUrna: "MARGARETE BALTA", partido: "DEM", sqCandidato: 120000890403}, 
//         {cargo: "VEREADOR", numeroCandidato: 40123, nomeCandidato: "RICARDO DE SENA PINHEIRO", nomeUrna: "RICARDO SENA", partido: "PSB", sqCandidato: 120001240725}, 
//         {cargo: "VICE-PREFEITO", numeroCandidato: 45, nomeCandidato: "MAURO CHRISTIANINI", nomeUrna: "MAURÃO", partido: "DEM", sqCandidato: 120000748341}, 
//         {cargo: "VEREADOR", numeroCandidato: 25000, nomeCandidato: "GUSTAVO LUIS DUO", nomeUrna: "GUSTAVO VETERINARIO", partido: "DEM", sqCandidato: 120000890413}, 
//         {cargo: "VEREADOR", numeroCandidato: 15151, nomeCandidato: "APARECIDA SOUZA NASCIMENTO", nomeUrna: "CIDA DECORAÇÕES", partido: "MDB", sqCandidato: 120000927959}, 
//         {cargo: "VEREADOR", numeroCandidato: 51017, nomeCandidato: "EDEMAR SHRODER", nomeUrna: "EDEMAR TA NA MÃO", partido: "PATRIOTA", sqCandidato: 120001015702}, 
//         {cargo: "VEREADOR", numeroCandidato: 10444, nomeCandidato: "JOSE DOMINGOS DOS SANTOS", nomeUrna: "ZEZÉ DO ESPETINHO", partido: "REPUBLICANOS", sqCandidato: 120001015575}, 
//         {cargo: "VICE-PREFEITO", numeroCandidato: 70, nomeCandidato: "ELIANE VINCENSI SIMÕES", nomeUrna: "ELIANE SIMÕES", partido: "AVANTE", sqCandidato: 120000856976}, 
//         {cargo: "VEREADOR", numeroCandidato: 25022, nomeCandidato: "HERMES BARBOSA PEREIRA", nomeUrna: "HERMES DO SINDICATO", partido: "DEM", sqCandidato: 120000890408}, 
//         {cargo: "PREFEITO", numeroCandidato: 70, nomeCandidato: "JEAMILTON DE OLIVEIRA BARBOSA", nomeUrna: "PROFESSOR JEAMILTON", partido: "AVANTE", sqCandidato: 120000856975}, 
//         {cargo: "VEREADOR", numeroCandidato: 13500, nomeCandidato: "CLAUDINEI LUIZ DAVILA", nomeUrna: "TADI", partido: "PT", sqCandidato: 120001118621}, 
//         {cargo: "VEREADOR", numeroCandidato: 25255, nomeCandidato: "JULIO CESAR DO CARMO OLIVEIRA", nomeUrna: "JULIO DO CAMINHÃO", partido: "DEM", sqCandidato: 120000890397}, 
//         {cargo: "VEREADOR", numeroCandidato: 51015, nomeCandidato: "LUZILENE BELTRAMIN BOTELHO", nomeUrna: "LUZILENE BELTRAMIN", partido: "PATRIOTA", sqCandidato: 120001015690}, 
//         {cargo: "VEREADOR", numeroCandidato: 40777, nomeCandidato: "PAULA ANDREIA MONTEIRO ECHEVERRIA", nomeUrna: "PAULINHA", partido: "PSB", sqCandidato: 120001240712}, 
//         {cargo: "VEREADOR", numeroCandidato: 25321, nomeCandidato: "JAIME BARBOSA TALAVEIRA", nomeUrna: "JAIME TALAVEIRA", partido: "DEM", sqCandidato: 120000890400}, 
//         {cargo: "VEREADOR", numeroCandidato: 51013, nomeCandidato: "EDIO MULLER", nomeUrna: "EDIO MULLER", partido: "PATRIOTA", sqCandidato: 120001015701}, 
//         {cargo: "VEREADOR", numeroCandidato: 25611, nomeCandidato: "ILSON PORTELA", nomeUrna: "CATITO", partido: "DEM", sqCandidato: 120000890398}, 
//         {cargo: "VICE-PREFEITO", numeroCandidato: 20, nomeCandidato: "PAULO RICARDO PERUZATTO", nomeUrna: "PAULO RICARDO PERUZATTO", partido: "PSC", sqCandidato: 120000890127}, 
//         {cargo: "VEREADOR", numeroCandidato: 51123, nomeCandidato: "JEFERSON APARECIDO LOPES", nomeUrna: "JEFERSON LOPES", partido: "PATRIOTA", sqCandidato: 120001015691}, 
//         {cargo: "VEREADOR", numeroCandidato: 51111, nomeCandidato: "NEIDE TEREZINHA DOS SANTOS", nomeUrna: "NEIDE SERRALHEIRA", partido: "PATRIOTA", sqCandidato: 120001015697}, 
//         {cargo: "VEREADOR", numeroCandidato: 70123, nomeCandidato: "PEDRO ACOSTA CANTERO", nomeUrna: "PEDRO CONSTRUTOR", partido: "AVANTE", sqCandidato: 120000858827}, 
//         {cargo: "VEREADOR", numeroCandidato: 15420, nomeCandidato: "DANIELA SERRA GAI", nomeUrna: "DANI SERRA", partido: "MDB", sqCandidato: 120000927961}, 
//         {cargo: "VEREADOR", numeroCandidato: 45444, nomeCandidato: "FELIPE ANDRE LEITE DE OLIVEIRA", nomeUrna: "FELIPE FEIJÃO", partido: "PSDB", sqCandidato: 120000860466}, 
//         {cargo: "VEREADOR", numeroCandidato: 15111, nomeCandidato: "RUDIMAR OLIVEIRA LAUTERT", nomeUrna: "RUDIMAR LAUTERT", partido: "MDB", sqCandidato: 120000927972}, 
//         {cargo: "VEREADOR", numeroCandidato: 51000, nomeCandidato: "ALAOR DOS SANTOS PADILHA", nomeUrna: "GUERREIRO", partido: "PATRIOTA", sqCandidato: 120001015686}, 
//         {cargo: "VEREADOR", numeroCandidato: 40999, nomeCandidato: "JOÃO DE ALMEIDA NUNES", nomeUrna: "JOÃO GAGO", partido: "PSB", sqCandidato: 120001240713}, 
//         {cargo: "VEREADOR", numeroCandidato: 51651, nomeCandidato: "ODAIR ROBERTO SCHWINN", nomeUrna: "BETO SCHWINN", partido: "PATRIOTA", sqCandidato: 120001015698}, 
//         {cargo: "VEREADOR", numeroCandidato: 45555, nomeCandidato: "PAULA FERNANDES ARGUELHO", nomeUrna: "PAULA FERNANDES", partido: "PSDB", sqCandidato: 120000860468}, 
//         {cargo: "VEREADOR", numeroCandidato: 25125, nomeCandidato: "ROSE RICARDO CORDEIRO", nomeUrna: "ROSE MANICURE", partido: "DEM", sqCandidato: 120000890407}, 
//         {cargo: "VEREADOR", numeroCandidato: 15010, nomeCandidato: "JONECI RODRIGUES ALVARES ZINI", nomeUrna: "PROFESSORA JONECI", partido: "MDB", sqCandidato: 120000927960}, 
//         {cargo: "VEREADOR", numeroCandidato: 15000, nomeCandidato: "MARIA DAS GRAÇAS ALVES DE LIMA", nomeUrna: "GRACINHA PERNAMBUCANA", partido: "MDB", sqCandidato: 120000927968}, 
//         {cargo: "VEREADOR", numeroCandidato: 70555, nomeCandidato: "REJANE LUIZA LANGE", nomeUrna: "PROFESSORA REJANE", partido: "AVANTE", sqCandidato: 120000858836}, 
//         {cargo: "VEREADOR", numeroCandidato: 25800, nomeCandidato: "ISAC FERNANDES ROMERO", nomeUrna: "ISAC ROMERO", partido: "DEM", sqCandidato: 120000890406}, 
//         {cargo: "VEREADOR", numeroCandidato: 10140, nomeCandidato: "PARDINHO TURIBIO SANABRIO", nomeUrna: "PADINHO", partido: "REPUBLICANOS", sqCandidato: 120001015559}, 
//         {cargo: "VEREADOR", numeroCandidato: 10291, nomeCandidato: "RODRIGO CHAMORRO VILALBA GONÇALVES", nomeUrna: "RODRIGO CHAMORRO", partido: "REPUBLICANOS", sqCandidato: 120001015569}, 
//         {cargo: "VEREADOR", numeroCandidato: 10123, nomeCandidato: "JOSIAS MARTINEZ VALDEZ", nomeUrna: "JOSIAS MARTINEZ", partido: "REPUBLICANOS", sqCandidato: 120001015560}, 
//         {cargo: "VEREADOR", numeroCandidato: 45345, nomeCandidato: "WANDERLEI ROQUE GONCALVES", nomeUrna: "WANDERLEI ROQUE", partido: "PSDB", sqCandidato: 120000860463}, 
//         {cargo: "VEREADOR", numeroCandidato: 45123, nomeCandidato: "ROBERT GUSTAVO ZEIMANN", nomeUrna: "ROBERT ZIEMANN", partido: "PSDB", sqCandidato: 120000860460}, 
//         {cargo: "VEREADOR", numeroCandidato: 10112, nomeCandidato: "ADAILTON GOMES SOUZA", nomeUrna: "ADAILTON CABELEIREIRO", partido: "REPUBLICANOS", sqCandidato: 120001015568}, 
//         {cargo: "VEREADOR", numeroCandidato: 40111, nomeCandidato: "GISLAINE DE MELO BRITES", nomeUrna: "GIH", partido: "PSB", sqCandidato: 120001240715}, 
//         {cargo: "VICE-PREFEITO", numeroCandidato: 10, nomeCandidato: "TELIANE ALVES BISOGNIN", nomeUrna: "DRA TELIANE", partido: "REPUBLICANOS", sqCandidato: 120001015366}, 
//         {cargo: "VEREADOR", numeroCandidato: 45111, nomeCandidato: "SERLEI MARISA MULLER MOSSMANN", nomeUrna: "SERLEI MOSSMANN", partido: "PSDB", sqCandidato: 120000860478}, 
//         {cargo: "VEREADOR", numeroCandidato: 40111, nomeCandidato: "GISLAINE DE MELO BRITES", nomeUrna: "GIH", partido: "PSB", sqCandidato: 120001240721}, 
//         {cargo: "PREFEITO", numeroCandidato: 27, nomeCandidato: "REGINALDO PEREIRA FERREIRA", nomeUrna: "REGINALDO FOTÓGRAFO", partido: "DC", sqCandidato: 120001200714}, 
//         {cargo: "VEREADOR", numeroCandidato: 40333, nomeCandidato: "JUSCELINO NUNES", nomeUrna: "JUSCELINO COWBOY", partido: "PSB", sqCandidato: 120001240724}, 
//         {cargo: "VEREADOR", numeroCandidato: 13777, nomeCandidato: "MÁRIO VERA SANCHES", nomeUrna: "MÁRIO VERA", partido: "PT", sqCandidato: 120001118623}, 
//         {cargo: "VEREADOR", numeroCandidato: 27010, nomeCandidato: "FLAVIO FERREIRA NERES", nomeUrna: "FLÁVIO KANU", partido: "DC", sqCandidato: 120001201410}, 
//         {cargo: "VEREADOR", numeroCandidato: 40070, nomeCandidato: "GILSON RODRIGUES DE ALMEIDA", nomeUrna: "ALEMÃO COITADINHO", partido: "PSB", sqCandidato: 120001240709}, 
//         {cargo: "VEREADOR", numeroCandidato: 51898, nomeCandidato: "CRISTIANO BERNY DUARTE", nomeUrna: "VERMELINHO DA JABIRACA", partido: "PATRIOTA", sqCandidato: 120001015703}, 
//         {cargo: "VEREADOR", numeroCandidato: 40040, nomeCandidato: "SIDINEI JORGE DO CARMO", nomeUrna: "COLORADO", partido: "PSB", sqCandidato: 120001240723}, 
//         {cargo: "VEREADOR", numeroCandidato: 10000, nomeCandidato: "VALDIR UBALDO DE BRITO", nomeUrna: "VALDIR DE BRITO", partido: "REPUBLICANOS", sqCandidato: 120001015573}, 
//         {cargo: "VEREADOR", numeroCandidato: 40040, nomeCandidato: "SIDINEI JORGE DO CARMO", nomeUrna: "COLORADO", partido: "PSB", sqCandidato: 120001240707}, 
//         {cargo: "VEREADOR", numeroCandidato: 40333, nomeCandidato: "JUSCELINO NUNES", nomeUrna: "JUSCELINO COWBOY", partido: "PSB", sqCandidato: 120001240717}, 
//         {cargo: "VEREADOR", numeroCandidato: 40456, nomeCandidato: "GELCI FIGUEIREDO OLIVEIRA", nomeUrna: "GELCI FIGUEIREDO", partido: "PSB", sqCandidato: 120001240718}, 
//         {cargo: "VEREADOR", numeroCandidato: 10234, nomeCandidato: "APARECIDA DE FATIMA DE ALMEIDA SILVA", nomeUrna: "FÁTIMA ALMEIDA", partido: "REPUBLICANOS", sqCandidato: 120001015572}, 
//         {cargo: "VEREADOR", numeroCandidato: 25678, nomeCandidato: "DANIEL RUIZ", nomeUrna: "DANIEL ESQUIVEL", partido: "DEM", sqCandidato: 120000890410}, 
//         {cargo: "VEREADOR", numeroCandidato: 10194, nomeCandidato: "EILENA DE SOUZA GUIMARAES", nomeUrna: "EILENA DE SOUZA", partido: "REPUBLICANOS", sqCandidato: 120001015567}, 
//         {cargo: "VEREADOR", numeroCandidato: 45045, nomeCandidato: "DIRLENE BASILIO NOVAES", nomeUrna: "DIRLENE NOVAES", partido: "PSDB", sqCandidato: 120000860470}, 
//         {cargo: "VICE-PREFEITO", numeroCandidato: 15, nomeCandidato: "LIDIANE BEATRIZ CHIESA MUNARETTO", nomeUrna: "DRA LIDIANE", partido: "MDB", sqCandidato: 120000742355}, 
//         {cargo: "VEREADOR", numeroCandidato: 13000, nomeCandidato: "MARCELO DUARTE", nomeUrna: "MARCELO PINTOR", partido: "PT", sqCandidato: 120001118616}, 
//         {cargo: "VEREADOR", numeroCandidato: 45633, nomeCandidato: "SIRLEI DA COSTA CARRIÇO", nomeUrna: "SIRLEI CARRIÇO", partido: "PSDB", sqCandidato: 120000860469}, 
//         {cargo: "VEREADOR", numeroCandidato: 70333, nomeCandidato: "ROBERTO ROGÉRIO DOS SANTOS DEPOORTER", nomeUrna: "ROBERTO DEPOORTER", partido: "AVANTE", sqCandidato: 120000858831}, 
//         {cargo: "VEREADOR", numeroCandidato: 51220, nomeCandidato: "BEZALIEL CRUZ", nomeUrna: "BEZA", partido: "PATRIOTA", sqCandidato: 120001015696}, 
//         {cargo: "VEREADOR", numeroCandidato: 10222, nomeCandidato: "OSEIAS CARVALHO RODRIGUES", nomeUrna: "OSEIAS ENFERMEIRO", partido: "REPUBLICANOS", sqCandidato: 120001015561}, 
//         {cargo: "VEREADOR", numeroCandidato: 25777, nomeCandidato: "KARINY CANDIDO RIOS", nomeUrna: "KARINY RIOS", partido: "DEM", sqCandidato: 120000890401}, 
//         {cargo: "VEREADOR", numeroCandidato: 70456, nomeCandidato: "GEISA FRANCO BARBOSA", nomeUrna: "GEISA BARBOSA", partido: "AVANTE", sqCandidato: 120000858830}, 
//         {cargo: "VEREADOR", numeroCandidato: 15616, nomeCandidato: "ANTÔNIO JOÃO MARÇAL DE SOUZA", nomeUrna: "NENÊ DA VISTA ALEGRE", partido: "MDB", sqCandidato: 120000927967}, 
//         {cargo: "VEREADOR", numeroCandidato: 51777, nomeCandidato: "VILMAR LUIS DE OLIVEIRA", nomeUrna: "VILMAR DA ERA DO GELO", partido: "PATRIOTA", sqCandidato: 120001015700}, 
//         {cargo: "VEREADOR", numeroCandidato: 51055, nomeCandidato: "ELISÂNGELA MARTINS TELES ARGENTA", nomeUrna: "ELISÂNGELA ARGENTA", partido: "PATRIOTA", sqCandidato: 120001015687}, 
//         {cargo: "VEREADOR", numeroCandidato: 15555, nomeCandidato: "LUDIMAR PORTELA", nomeUrna: "NEGO DO POVO", partido: "MDB", sqCandidato: 120000927958}, 
//         {cargo: "VEREADOR", numeroCandidato: 40789, nomeCandidato: "MARIA CRISTINA ALCANTARA JORGE", nomeUrna: "CRIS", partido: "PSB", sqCandidato: 120001240719}, 
//         {cargo: "VEREADOR", numeroCandidato: 51444, nomeCandidato: "ODILIA PERES BENITES", nomeUrna: "ODILIA PERES", partido: "PATRIOTA", sqCandidato: 120001015689}, 
//         {cargo: "VEREADOR", numeroCandidato: 40070, nomeCandidato: "GILSON RODRIGUES DE ALMEIDA", nomeUrna: "ALEMÃO COITADINHO", partido: "PSB", sqCandidato: 120001240708}, 
//         {cargo: "VEREADOR", numeroCandidato: 45222, nomeCandidato: "RENER BARBOSA PACHE", nomeUrna: "RENER BARBOSA", partido: "PSDB", sqCandidato: 120000860462}, 
//         {cargo: "VEREADOR", numeroCandidato: 45333, nomeCandidato: "ERLEI PIRES DIAS", nomeUrna: "PROFESSOR ERLEI", partido: "PSDB", sqCandidato: 120000860464}, 
//         {cargo: "VEREADOR", numeroCandidato: 27888, nomeCandidato: "ÉDERSON ROLA VELASQUES", nomeUrna: "ÉDERSON KURU", partido: "DC", sqCandidato: 120001201407}, 
//         {cargo: "VEREADOR", numeroCandidato: 10345, nomeCandidato: "ALTAMIRO NASCIMENTO RIBEIRO", nomeUrna: "ALTAMIRO", partido: "REPUBLICANOS", sqCandidato: 120001015565}, 
//         {cargo: "VEREADOR", numeroCandidato: 15222, nomeCandidato: "MARCELINA RAMONA AMARILHA IBARRA", nomeUrna: "MARCELINA IBARRA", partido: "MDB", sqCandidato: 120000927966}, 
//         {cargo: "VEREADOR", numeroCandidato: 40173, nomeCandidato: "ADAUTO DE SOUZA", nomeUrna: "ADAUTO SOUZA", partido: "PSB", sqCandidato: 120001240710}, 
//         {cargo: "VEREADOR", numeroCandidato: 13455, nomeCandidato: "ADÉLIA MORAIS", nomeUrna: "DONA ADELIA", partido: "PT", sqCandidato: 120001118615}, 
//         {cargo: "VEREADOR", numeroCandidato: 70157, nomeCandidato: "MARCELINO MATEUS SILVA PROENÇA", nomeUrna: "MARCELINO TOCHA", partido: "AVANTE", sqCandidato: 120000858833}, 
//         {cargo: "VEREADOR", numeroCandidato: 40555, nomeCandidato: "ROSIMEIRE FERREIRA DA SILVA", nomeUrna: "ROSE", partido: "PSB", sqCandidato: 120001240727}, 
//         {cargo: "VEREADOR", numeroCandidato: 51999, nomeCandidato: "RODIMARA BARBOSA PACHE KARACZACK", nomeUrna: "MARA BARBOSA", partido: "PATRIOTA", sqCandidato: 120001015693}, 
//         {cargo: "VEREADOR", numeroCandidato: 15678, nomeCandidato: "ÁLVARO MEINERZ", nomeUrna: "ALEMÃO DA ROÇA", partido: "MDB", sqCandidato: 120000927971}, 
//         {cargo: "VEREADOR", numeroCandidato: 13333, nomeCandidato: "EMILIANO SANTANA", nomeUrna: "BYLLA", partido: "PT", sqCandidato: 120001118618}, 
//         {cargo: "VEREADOR", numeroCandidato: 15333, nomeCandidato: "VERGÍNIO DA SILVA", nomeUrna: "VERGÍLIO DA BANCA", partido: "MDB", sqCandidato: 120000927962}, 
//         {cargo: "VEREADOR", numeroCandidato: 51789, nomeCandidato: "FRANCISCO ELIEUDO PAIVA OLIVEIRA", nomeUrna: "CEARÁ", partido: "PATRIOTA", sqCandidato: 120001015684}, 
//         {cargo: "VEREADOR", numeroCandidato: 13513, nomeCandidato: "MARIA EVA LOPES", nomeUrna: "DONA EVA", partido: "PT", sqCandidato: 120001118620}, 
//         {cargo: "VEREADOR", numeroCandidato: 10007, nomeCandidato: "THALISSON FRANCISCO DA SILVA", nomeUrna: "THALISSON FRANCISCO", partido: "REPUBLICANOS", sqCandidato: 120001015570}, 
//         {cargo: "VEREADOR", numeroCandidato: 51222, nomeCandidato: "OSEIAS RODRIGUES ESCOBAL", nomeUrna: "OSÉIAS FERVO", partido: "PATRIOTA", sqCandidato: 120001015695}, 
//         {cargo: "VEREADOR", numeroCandidato: 25300, nomeCandidato: "ALESSANDRA SANTANA CELESTINO MATOS", nomeUrna: "ALESSANDRA CELESTINO", partido: "DEM", sqCandidato: 120000890409}, 
//         {cargo: "VEREADOR", numeroCandidato: 13123, nomeCandidato: "NICODEMOS FRANCISCO REIS", nomeUrna: "NICODEMOS", partido: "PT", sqCandidato: 120001118624}, 
//         {cargo: "VEREADOR", numeroCandidato: 45611, nomeCandidato: "JERONIMO DE MENEZES", nomeUrna: "GALO", partido: "PSDB", sqCandidato: 120000860467}, 
//         {cargo: "VEREADOR", numeroCandidato: 70500, nomeCandidato: "MÁRCIO SALES MAGALHÃES", nomeUrna: "BISPO MÁRCIO SALES", partido: "AVANTE", sqCandidato: 120000858828}, 
//         {cargo: "VEREADOR", numeroCandidato: 45645, nomeCandidato: "NELSON JOSE DOS SANTOS", nomeUrna: "NELSON LORDS", partido: "PSDB", sqCandidato: 120000860477}, 
        
//     ];


//     function gerarTabela(div, header, body) {

//         div.innerHTML = "";
//         let thead = div.createTHead();
//         let row = thead.insertRow();
//         for (var i = 0; i < header.length; i++) {
//             let headerCell = document.createElement("TH");
//             headerCell.innerHTML = header[i];
//             row.appendChild(headerCell);
//         } // for

//         let tbody = div.createTBody();

//         for (var i = 0; i < body.length; i++) {
//             row = tbody.insertRow();
//             let chaves = Object.keys(body[i]);
//             for (var k = 0; k < chaves.length-1; k++) {
//                 let cell = row.insertCell();
//                 cell.innerHTML = body[i][chaves[k]];
//             }// for
//         }// for
//     }// function

//     gerarTabela(divTabela, ["cargo", "núm.", "nome", "urna", "partido"], candidatos);

// })();
